const people = [
  {
    firstName: "John",
    lastName: "Doe",
    age: 32,
    city: "New York",
    state: "NY",
    favoriteFood: "chicken",
  },
  {
    firstName: "Mary",
    lastName: "Smith",
    age: 24,
    city: "Los Angeles",
    state: "CA",
    favoriteFood: "burgers",
  },
  {
    firstName: "Peter",
    lastName: "Brown",
    age: 45,
    city: "Chicago",
    state: "IL",
    favoriteFood: "fries",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    age: 29,
    city: "San Francisco",
    state: "CA",
    favoriteFood: "chicken",
  },
  {
    firstName: "David",
    lastName: "Lee",
    age: 38,
    city: "Seattle",
    state: "WA",
    favoriteFood: "burgers",
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    age: 27,
    city: "Boston",
    state: "MA",
    favoriteFood: "fries",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    age: 41,
    city: "Dallas",
    state: "TX",
    favoriteFood: "chicken",
  },
  {
    firstName: "Amy",
    lastName: "Nguyen",
    age: 31,
    city: "Houston",
    state: "TX",
    favoriteFood: "burgers",
  },
  {
    firstName: "Brian",
    lastName: "Kim",
    age: 22,
    city: "Miami",
    state: "FL",
    favoriteFood: "fries",
  },
  {
    firstName: "Jasmine",
    lastName: "Garcia",
    age: 35,
    city: "Phoenix",
    state: "AZ",
    favoriteFood: "chicken",
  },
  {
    firstName: "Robert",
    lastName: "Ramirez",
    age: 26,
    city: "Denver",
    state: "CO",
    favoriteFood: "burgers",
  },
  {
    firstName: "Julia",
    lastName: "Martinez",
    age: 39,
    city: "San Diego",
    state: "CA",
    favoriteFood: "fries",
  },
  {
    firstName: "Timothy",
    lastName: "Chen",
    age: 28,
    city: "San Jose",
    state: "CA",
    favoriteFood: "chicken",
  },
  {
    firstName: "Samantha",
    lastName: "Chang",
    age: 33,
    city: "Atlanta",
    state: "GA",
    favoriteFood: "burgers",
  },
  {
    firstName: "William",
    lastName: "Wang",
    age: 30,
    city: "New Orleans",
    state: "LA",
    favoriteFood: "fries",
  },
];

export default people;
